In [18]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('/content/Global_Superstore2.csv', encoding='latin1')
df.sample(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
19661,29297,IN-2014-71095,02-12-2014,02-12-2014,Same Day,NP-18700,Nora Preis,Consumer,Tegal,Jawa Tengah,...,OFF-AR-10004424,Office Supplies,Art,"Boston Markers, Blue",115.5006,6,0.27,-34.9794,12.86,Medium
43003,36300,CA-2013-155033,08-10-2013,13-10-2013,Standard Class,CC-12475,Cindy Chapman,Consumer,Los Angeles,California,...,OFF-PA-10000143,Office Supplies,Paper,Astroparche Fine Business Paper,10.5600,2,0.00,5.0688,1.61,High
14525,49187,ZA-2014-9750,27-02-2014,03-03-2014,Second Class,TS-11205,Thomas Seio,Corporate,Ndola,Copperbelt,...,TEC-MEM-10002202,Technology,Accessories,"Memorex Router, USB",246.4200,1,0.00,19.7100,20.62,Medium
46903,21131,IN-2013-22648,14-05-2013,20-05-2013,Standard Class,SF-20065,Sandra Flanagan,Consumer,Ratlam,Madhya Pradesh,...,OFF-ST-10000327,Office Supplies,Storage,"Smead Folders, Wire Frame",33.1200,2,0.00,4.6200,0.91,Medium
29419,17087,ES-2013-2930577,07-02-2013,11-02-2013,Standard Class,DJ-13510,Don Jones,Corporate,Lorca,Murcia,...,OFF-SU-10004446,Office Supplies,Supplies,"Acme Scissors, Steel",49.6800,2,0.00,23.3400,5.76,High
50375,48789,TU-2013-7990,29-07-2013,29-07-2013,Same Day,TB-11250,Tim Brockman,Consumer,Sivas,Sivas,...,OFF-FEL-10002158,Office Supplies,Storage,"Fellowes Folders, Blue",10.5600,1,0.60,-2.6400,0.30,Medium
46125,37479,CA-2012-158421,21-09-2012,26-09-2012,Standard Class,GB-14575,Giulietta Baptist,Consumer,Columbia,South Carolina,...,OFF-BI-10000050,Office Supplies,Binders,"Angle-D Binders with Locking Rings, Label Holders",14.6000,2,0.00,6.8620,1.04,Medium
15512,9140,MX-2011-120502,18-06-2011,23-06-2011,Standard Class,SW-20275,Scott Williamson,Consumer,Reynosa,Tamaulipas,...,TEC-AC-10000692,Technology,Accessories,"Logitech Keyboard, Erganomic",234.2000,5,0.00,4.6000,18.79,Medium
419,39309,CA-2014-120138,26-05-2014,26-05-2014,Same Day,TB-21625,Trudy Brown,Consumer,New York City,New York,...,OFF-BI-10004519,Office Supplies,Binders,GBC DocuBind P100 Manual Binding Machine,663.9200,5,0.20,207.4750,314.27,Critical
21624,50254,SA-2013-3980,06-02-2013,06-02-2013,Same Day,SJ-10125,Sanjit Jacobs,Home Office,Riyadh,Ar Riyad,...,FUR-SAF-10002757,Furniture,Chairs,"SAFCO Rocking Chair, Red",134.9100,1,0.00,6.7200,10.88,Medium

In [29]:
df.isna().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [30]:
df.shape

(51290, 24)

In [36]:
df.dropna(subset=['Postal Code'], inplace=True)
#postal code has many missing values and was not used in dashboard insights

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.to_csv('cleaned.csv')